language: objective-c
osx_image: xcode9.1

# xcode_project: Demo/SmileViewControllerDemo.xcodeproj
# xcode_scheme: SmileViewControllerDemo

script:
  xcodebuild clean build
  -sdk iphonesimulator
  -project Demo/SmileViewControllerDemo.xcodeproj
  -scheme SmileViewControllerDemo
  CODE_SIGNING_REQUIRED=NO

after_success:
  - bash <(curl -s https://codecov.io/bash)